### ISSUE TITLE
GateKeeper is not sending message to #check-point, not assigning "Member" role

### ISSUE THREAD

**Issue by kwilk1984** [kwilk1984/GateKeeper#1]
GateKeeper is not sending welcome message to the designated channel and is not assigning the "Member" role as designed.  This is resulting in the need for manual assignment of member role in server.

```
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "GateKeeper.py", line 39, in on_member_join
    await channel.send(f'Hello {member}, please proceed to #customs and agree to the rules.')
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/abc.py", line 904, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

```

**Comment by kwilk1984** [comment]
Found issue with incorrect channel ID corrected, but now seems that there is a permissions issue.
```
$ Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "./Documents/Repositories/GateKeeper/GateKeeper.py", line 39, in on_member_join
    await channel.send(f'Hello {member}, please proceed to #customs and agree to the rules to become a member.')
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/abc.py", line 904, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```
Will need to look at what permissions are required.

**Comment by kwilk1984** [comment]
Double checked and recreated permissions.  At this point I am going to let this run.

**Comment by kwilk1984** [comment]
Still is not sending messages and producing error:
```
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "./Documents/Repositories/GateKeeper/GateKeeper.py", line 39, in on_member_join
    await channel.send(f'Hello {member}, please proceed to #customs and agree to the rules to become a member.')
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/abc.py", line 904, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/kwilkins/.local/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

**Comment by kwilk1984** [comment]
Removed the function to send message when member joins.
